FROM golang:1.17-bullseye as builder

WORKDIR /src

RUN apt-get update && \
    apt-get install make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . /src
RUN make build

FROM gcr.io/distroless/base-debian11

COPY --from=builder /src/bin/* /

ENTRYPOINT ["/go-webapp"]
