FROM golang:1.17-buster as builder

WORKDIR /src

RUN apt-get update && \
    apt-get install -y make

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . /src
RUN make build

FROM gcr.io/distroless/base-debian10

COPY --from=builder /src/bin/* /

ENTRYPOINT ["/go-webapp"]
