FROM golang:1.17-buster

WORKDIR /src

RUN apt-get update && \
    apt-get install -y make

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . /src
RUN make build

ENTRYPOINT ["/src/bin/go-webapp"]
